osx_image: xcode10.2
language: objective-c

# Build with tests
script:
- pod repo update
- pod lib lint --verbose --allow-warnings
- xcodebuild -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' test
