osx_image: xcode10.2
language: objective-c

notifications:
  email: false

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: cocoapods

before_install:
  - gem install cocoapods -v '~> 1.7.0' --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

jobs:
  include:
    - stage: lint
      script:
        - pod lib lint --allow-warnings

    - stage: test
      before_install: mv .github/VerticalTree.podspec .
      script:
        - rm -rf ~/Library/Developer/Xcode/DerivedData/
        - cd Demo
        - pod install
        - xcodebuild clean build -workspace Demo.xcworkspace -scheme Demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c

    - stage: deploy
      if: tag IS present AND branch = master
      before_script:
        - echo 'current tag -> $TRAVIS_TAG'
        - sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" VerticalTree.podspec
      script:
        - set -eo pipefail
        - pod trunk push --verbose --allow-warnings | ruby -e 'ARGF.each{ print "." }'
        