osx_image: xcode10.2
language: objective-c

notifications:
  email: false

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: cocoapods
podfile: Podfile

before_install:
  - gem install cocoapods -v '~> 1.7.0' --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

# Build with tests
# script:
# - pod repo update
# - pod lib lint --allow-warnings
# - xcodebuild clean test -workspace Demo/Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6'

jobs:
  include:
    - stage: lint
      before_install: mv .github/VerticalTree.podspec .
      script:
        - pod lib lint --allow-warnings

    - stage: test
      before_install: mv .github/VerticalTree.podspec .
      script:
        - rm -rf ~/Library/Developer/Xcode/DerivedData/
        - cd Demo
        - pod install
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c

    - stage: deploy
      if: tag IS present
      before_script: |
        - mv .github/VerticalTree.podspec .
        - echo tag: $TRAVIS_TAG
        - sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" VerticalTree.podspec
      script: |
        - set -eo pipefail
        - pod trunk push --verbose --allow-warnings | ruby -e 'ARGF.each{ print "." }'
        